name: Spursy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#001a57'
    - '#ffffff'
    - '#3e4f75'
    - '#7986a1'
    - '#c7cfdb'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 1
purpose:
  - name: engagement
    item: 'null'
    url: null
